// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:convert';
import 'dart:typed_data';

import 'package:amap_map_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/services.dart';
import 'package:foundation_fluttify/foundation_fluttify.dart';

typedef void MapViewCreatedCallback(com_amap_api_maps_MapView controller);
typedef Future<void> _OnAndroidViewDispose();

class AMapNaviView_Android extends StatefulWidget {
  const AMapNaviView_Android({
    Key key,
    this.onViewCreated,
    this.onDispose,
  }) : super(key: key);

  final MapViewCreatedCallback onViewCreated;
  final _OnAndroidViewDispose onDispose;

  @override
  _AMapNaviView_AndroidState createState() => _AMapNaviView_AndroidState();
}

class _AMapNaviView_AndroidState extends State<AMapNaviView_Android> {
  @override
  Widget build(BuildContext context) {
    final gestureRecognizers = <Factory<OneSequenceGestureRecognizer>>[
      Factory<OneSequenceGestureRecognizer>(() => EagerGestureRecognizer()),
    ].toSet();

    final messageCodec = StandardMessageCodec();
    return AndroidView(
      viewType: 'me.yohom/com.amap.api.maps.AMapNaviView',
      gestureRecognizers: gestureRecognizers,
      onPlatformViewCreated: _onViewCreated,
      creationParamsCodec: messageCodec,
    );
  }

  void _onViewCreated(int id) {}

  @override
  void dispose() {
    super.dispose();
  }
}
